language: ruby
env: RACK_ENV=development CODECLIMATE_REPO_TOKEN=46b1437490b7273b5c7a72c1ac692c7d511aa3794adcf41d4cc7c574bbf35382
rvm:
- 2.6.3
addons:
  code_climate:
    repo_token: 46b1437490b7273b5c7a72c1ac692c7d511aa3794adcf41d4cc7c574bbf35382
deploy:
  provider: rubygems
  api_key:
    secure: GTBol3gRgtzJjXe3SExX2S4K9sVghXY1om6wfhqSrOoDa61HWauLTmzuBr2c43bAdXMDBYZpnXVTuE7wjTWlZzAJ0brIQsq9zW3jZuydnkxj0/2Bo4+ezvGWiVNefQVKT8dCCfqjUWppgfNqc2vMXWsXu67iuvZF9magzCnZvy0=
  gem: mumukit-bridge
  on:
    tags: true
    repo: mumuki/mumukit-bridge
